version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: always
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt
    depends_on:
      - telegram-bot
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
