[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker bot_new:app"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
PORT = "$PORT"
RAILWAY_HEALTHCHECK_TIMEOUT_SEC = 600  # 10 минут для сложных задач
