[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
startCommand = "uvicorn bot_new:app --host 0.0.0.0 --port $PORT"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
PORT = "$PORT"
RAILWAY_HEALTHCHECK_TIMEOUT_SEC = 600  # 10 минут для сложных задач
