[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
startCommand = "python bot_new.py"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
PORT = "$PORT"
