name: Deploy to Timeweb Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Trigger Timeweb Cloud Deployment
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TIMEWEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.timeweb.cloud/v1/apps/deploy \
          -d '{
            "app_id": "${{ secrets.TIMEWEB_APP_ID }}",
            "branch": "master",
            "commit_hash": "${{ github.sha }}"
          }'
